name: Generate Czech Content

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 9 AM UTC

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Ensure directory exists
        run: mkdir -p content/posts-cs
        
      - name: Generate Czech content
        run: node scripts/generate-czech-content.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
      - name: Commit changes
        run: |
          git add content/posts-cs
          git add public/images
          git commit -m "chore: add Czech content for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push 