name: Generate German Content

on:
  # Manual trigger
  workflow_dispatch:
  
  # Scheduled trigger - every day at 10 AM UTC
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Ensure directory existence
        run: |
          mkdir -p content/posts-de
          mkdir -p public/images/unsplash
          mkdir -p public/images/authors/de
      
      - name: Generate German content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: node scripts/generate-german-content.js
      
      - name: Sync with remote
        run: git pull origin main --rebase
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: add new German article [skip ci]"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
          push_options: "--force" 