name: Generate Czech Content

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 10 * * *'  # 10 AM UTC, every day

permissions:
  contents: write  # Permission to write to the repository

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Ensure directories exist
        run: mkdir -p content/posts-cs public/images/unsplash public/images/authors
      
      - name: Generate Czech Content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: node scripts/generate-czech-content.js
      
      - name: Sync with remote
        run: |
          git fetch origin
          git pull --rebase origin main
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add content/posts-cs public/images/unsplash public/images/authors
          git commit -m "chore: auto-generated Czech article [skip ci]" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 